#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Split IR paired FASTQ files by sample primer barcode.

IR read layout:
    R1: [10 bp UMI][8 bp sample primer barcode][insert]
    R2: [insert]

The sample/barcode mapping is read exclusively from the CSV generated by
``match_sample_barcode.py``. In ``raw`` mode matching R1 reads are written
after removing the UMI and primer barcode, with ``#<UMI>`` added to both paired
headers. In ``presplit`` mode the existing tagged FASTQ is validated and
adopted without a second barcode trim. Both modes publish the same compressed
read-to-UMI sidecar before clean-header removes the tag. Plain and gzip FASTQ
are accepted. Outputs preserve ``<Lane>/<pair_stem>/<sample_id>/`` hierarchy.
"""

from __future__ import annotations

import csv
import gzip
import hashlib
import json
import os
import posixpath
import re
import shutil
import sys
import tempfile
import time
import unicodedata
import zipfile
import atexit
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from threading import Lock
from typing import Iterable, TextIO
from xml.etree import ElementTree as ET

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tools.pipeline_config import load_config
os.environ.setdefault("SCIGBLAST_CONFIG", str(Path(__file__).resolve().parent / "00.pipeline_config.env"))
load_config()


PROJECT_ROOT = Path(__file__).resolve().parents[1]
BRANCH_ROOT = PROJECT_ROOT
OUTPUT_ROOT = Path(os.environ.get("SCIGBLAST_OUTPUT_ROOT", "") or str(BRANCH_ROOT / "output"))
# =========================
# Edit these global parameters before running. The cutter consumes only the
# mapping summary; submission and barcode-reference files belong to the
# preceding match_sample_barcode.py step.
# =========================
DATASET_LABEL = os.environ.get("SCIGBLAST_DATASET_LABEL", "").strip()
if DATASET_LABEL:
    _default_input = OUTPUT_ROOT / "02.fastp" / DATASET_LABEL / "data"
    _default_output = OUTPUT_ROOT / "03.IR_split_output" / DATASET_LABEL
    _default_summary = OUTPUT_ROOT / "01.match" / DATASET_LABEL / "sample_barcode_summary.csv"
else:
    _default_input = OUTPUT_ROOT / "02.fastp" / "data"
    _default_output = OUTPUT_ROOT / "03.IR_split_output"
    _default_summary = OUTPUT_ROOT / "01.match" / "sample_barcode_summary.csv"
INPUT_DIR = Path(os.environ.get("SCIGBLAST_IR_INPUT", str(_default_input)))
OUTPUT_DIR = Path(os.environ.get("SCIGBLAST_IR_OUTPUT", str(_default_output)))
INPUT_MODE = os.environ.get("SCIGBLAST_IR_INPUT_MODE", "raw").strip().lower()
MAPPING_SUMMARY: Path | None = Path(os.environ.get(
    "SCIGBLAST_IR_MAPPING_SUMMARY",
    str(_default_summary),
))
UMI_LENGTH = int(os.environ.get("SCIGBLAST_IR_UMI_LENGTH", "10"))
WORKERS = int(os.environ.get("SCIGBLAST_IR_WORKERS", "1"))
COMPRESSLEVEL = int(os.environ.get("SCIGBLAST_IR_COMPRESSLEVEL", "1"))
# Resume mode: per-pair plain-text parts and JSON checkpoints allow read-level
# continuation; complete pairs are skipped only after a DONE checkpoint.  The
# checkpoint is batched because per-read atomic writes make large FASTQ runs
# dominated by metadata I/O.
SKIP_EXISTING = True
DRY_RUN = False
SUMMARY_PATH: Path | None = None
PROGRESS_SUMMARY_PATH: Path | None = None
# Human-readable progress and durable checkpoints are written periodically.
CHECKPOINT_EVERY = max(1, int(os.environ.get("SCIGBLAST_IR_CHECKPOINT_EVERY", "10000")))
PROGRESS_FLUSH_EVERY = max(1, int(os.environ.get("SCIGBLAST_IR_PROGRESS_FLUSH_EVERY", "1000")))
PROGRESS_DISPLAY_EVERY = 1000
PID_FILE = Path(__file__).resolve().parent / ".split_barcode.pid"
FASTQ_SUFFIXES = (".fastq.gz", ".fq.gz", ".fastq", ".fq")
CANONICAL_R1_SUFFIX = "_R1.fq.gz"
CANONICAL_R2_SUFFIX = "_R2.fq.gz"
SAMPLE_BOUNDARY_RE = r"(?<![A-Za-z0-9]){sample}(?![A-Za-z0-9])"
PROGRESS_FIELDS = ["pair_key", "sample_id", "processed_reads", "matched_reads", "mismatch_reads",
                   "short_reads", "status", "error", "updated_at", "r1", "r2", "output_r1", "output_r2"]
PROGRESS_LOCK = Lock()
PROGRESS_ROWS: dict[str, dict[str, str]] = {}
PROGRESS_UPDATES = 0
NS_MAIN = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
NS_REL = "http://schemas.openxmlformats.org/package/2006/relationships"
NS_DOC_REL = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"


@dataclass(frozen=True)
class SubmissionRecord:
    sample_id: str
    barcode_candidate: str
    barcode_name: str
    barcode_sequence: str


@dataclass(frozen=True)
class FastqPair:
    sample: SubmissionRecord
    stem: str
    r1: Path
    r2: Path
    output_prefix: str = ""


@dataclass
class PairResult:
    sample_id: str
    barcode_candidate: str
    barcode_name: str
    barcode_sequence: str
    r1: str
    r2: str
    output_r1: str = ""
    output_r2: str = ""
    umi_sidecar: str = ""
    total_reads: int = 0
    matched_reads: int = 0
    mismatch_reads: int = 0
    short_reads: int = 0
    processed_reads: int = 0
    resumed_from: int = 0
    status: str = "OK"
    error: str = ""


def normalize_text(value: object) -> str:
    text = unicodedata.normalize("NFKC", str(value or "")).replace("\ufeff", "")
    return re.sub(r"\s+", "", text).casefold()


def display_text(value: object) -> str:
    return unicodedata.normalize("NFKC", str(value or "")).strip()


def register_process() -> None:
    """Create a stale-safe PID file for IR_split/stop.sh."""
    PID_FILE.parent.mkdir(parents=True, exist_ok=True)
    if PID_FILE.exists():
        try:
            old_pid = int(PID_FILE.read_text(encoding="utf-8").strip())
            os.kill(old_pid, 0)
        except (FileNotFoundError, ProcessLookupError, PermissionError, ValueError, OSError):
            PID_FILE.unlink(missing_ok=True)
        else:
            raise SystemExit(f"split_barcode.py is already running (PID {old_pid}); use IR_split/stop.sh")
    PID_FILE.write_text(str(os.getpid()), encoding="utf-8")

    def cleanup() -> None:
        try:
            if PID_FILE.read_text(encoding="utf-8").strip() == str(os.getpid()):
                PID_FILE.unlink(missing_ok=True)
        except (FileNotFoundError, OSError):
            pass

    atexit.register(cleanup)


def _column_number(cell_ref: str) -> int:
    match = re.match(r"[A-Za-z]+", cell_ref)
    if not match:
        raise ValueError(f"Invalid spreadsheet cell reference: {cell_ref}")
    number = 0
    for char in match.group(0).upper():
        number = number * 26 + ord(char) - ord("A") + 1
    return number - 1


def _xml_text(element: ET.Element) -> str:
    return "".join(node.text or "" for node in element.iter(f"{{{NS_MAIN}}}t"))


def _worksheet_path(archive: zipfile.ZipFile, sheet_name: str | None) -> str:
    workbook = ET.fromstring(archive.read("xl/workbook.xml"))
    rels = ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))
    rel_map = {
        rel.attrib["Id"]: rel.attrib["Target"]
        for rel in rels.findall(f"{{{NS_REL}}}Relationship")
    }
    sheets = workbook.find(f"{{{NS_MAIN}}}sheets")
    if sheets is None:
        raise ValueError("Workbook contains no worksheets")
    chosen = None
    for sheet in sheets:
        if sheet_name is None or sheet.attrib.get("name") == sheet_name:
            chosen = sheet
            break
    if chosen is None:
        available = ", ".join(sheet.attrib.get("name", "") for sheet in sheets)
        raise ValueError(f"Worksheet {sheet_name!r} not found; available: {available}")
    rel_id = f"{{{NS_DOC_REL}}}id"
    target = rel_map[chosen.attrib[rel_id]]
    return posixpath.normpath(posixpath.join("xl", target)).lstrip("/")


def read_xlsx_rows(path: Path, sheet_name: str | None) -> list[list[str]]:
    if not path.is_file():
        raise FileNotFoundError(f"Submission workbook not found: {path}")
    with zipfile.ZipFile(path) as archive:
        shared: list[str] = []
        if "xl/sharedStrings.xml" in archive.namelist():
            root = ET.fromstring(archive.read("xl/sharedStrings.xml"))
            shared = [_xml_text(si) for si in root.findall(f"{{{NS_MAIN}}}si")]
        sheet = ET.fromstring(archive.read(_worksheet_path(archive, sheet_name)))
        rows: list[list[str]] = []
        sheet_data = sheet.find(f"{{{NS_MAIN}}}sheetData")
        if sheet_data is None:
            return rows
        for row in sheet_data:
            values: dict[int, str] = {}
            max_col = -1
            for cell in row.findall(f"{{{NS_MAIN}}}c"):
                col = _column_number(cell.attrib.get("r", "A1"))
                max_col = max(max_col, col)
                cell_type = cell.attrib.get("t")
                if cell_type == "inlineStr":
                    value = _xml_text(cell)
                else:
                    value_node = cell.find(f"{{{NS_MAIN}}}v")
                    value = value_node.text if value_node is not None else ""
                    if cell_type == "s" and value:
                        value = shared[int(value)]
                    elif cell_type == "b":
                        value = "TRUE" if value == "1" else "FALSE"
                values[col] = value
            rows.append([values.get(index, "") for index in range(max_col + 1)])
        return rows


def _resolve_header(headers: list[str], requested: str, kind: str) -> int:
    normalized = [normalize_text(value) for value in headers]
    target = normalize_text(requested)
    if target in normalized:
        return normalized.index(target)
    if kind == "barcode":
        candidates = [
            index for index, value in enumerate(normalized)
            if "barcode" in value and any(token in value for token in ("候选", "引物", "primer", "candidate"))
        ]
        if len(candidates) == 1:
            return candidates[0]
    raise ValueError(f"Could not resolve {kind} column {requested!r}; headers={headers!r}")


def normalize_barcode_name(value: object) -> str:
    text = display_text(value).upper().replace(" ", "")
    match = re.fullmatch(r"BC[_-]?(\d+)", text) or re.fullmatch(r"(\d+)", text)
    if not match:
        raise ValueError(f"Invalid primer barcode candidate: {text!r}")
    return str(int(match.group(1)))


def load_barcode_reference(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise FileNotFoundError(f"Barcode CSV not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            raise ValueError("Barcode CSV has no header")
        fields = {normalize_text(field): field for field in reader.fieldnames}
        name_field = fields.get("name")
        seq_field = fields.get("seq")
        if not name_field or not seq_field:
            raise ValueError("Barcode CSV must contain name and seq columns")
        reference: dict[str, str] = {}
        for row in reader:
            raw_name = display_text(row.get(name_field, ""))
            raw_seq = display_text(row.get(seq_field, "")).upper()
            if not raw_name and not raw_seq:
                continue
            try:
                name = str(int(float(raw_name)))
            except ValueError as exc:
                raise ValueError(f"Invalid barcode reference name: {raw_name!r}") from exc
            if not re.fullmatch(r"[ACGT]{8}", raw_seq):
                raise ValueError(f"Barcode {name} must be exactly 8 A/C/G/T bases: {raw_seq!r}")
            if name in reference and reference[name] != raw_seq:
                raise ValueError(f"Conflicting barcode reference for {name}")
            reference[name] = raw_seq
    if not reference:
        raise ValueError("Barcode CSV contains no records")
    return reference


def load_submission(path: Path, sheet_name: str | None, sample_column: str, barcode_column: str,
                    reference: dict[str, str]) -> dict[str, SubmissionRecord]:
    rows = read_xlsx_rows(path, sheet_name)
    if not rows:
        raise ValueError("Submission workbook is empty")
    sample_target = normalize_text(sample_column)
    header_index = None
    sample_index = barcode_index = None
    for index, row in enumerate(rows):
        normalized = [normalize_text(value) for value in row]
        if sample_target in normalized:
            header_index = index
            sample_index = normalized.index(sample_target)
            barcode_index = _resolve_header(row, barcode_column, "barcode")
            break
    if header_index is None or sample_index is None or barcode_index is None:
        raise ValueError(f"Submission column not found: {sample_column!r}")

    records: dict[str, SubmissionRecord] = {}
    for row in rows[header_index + 1:]:
        sample_id = display_text(row[sample_index] if sample_index < len(row) else "")
        candidate = display_text(row[barcode_index] if barcode_index < len(row) else "")
        if not sample_id or normalize_text(sample_id) == sample_target:
            continue
        barcode_name = normalize_barcode_name(candidate)
        if barcode_name not in reference:
            raise ValueError(f"Barcode {candidate!r} ({barcode_name}) is absent from {path}")
        record = SubmissionRecord(sample_id, candidate, barcode_name, reference[barcode_name])
        key = normalize_text(sample_id)
        previous = records.get(key)
        if previous and previous != record:
            raise ValueError(f"Conflicting duplicate Sample ID in submission: {sample_id}")
        records[key] = record
    if not records:
        raise ValueError("No usable Sample ID records found in submission")
    return records


def fastq_suffix(path: Path) -> str | None:
    lower = path.name.lower()
    for suffix in FASTQ_SUFFIXES:
        if lower.endswith(suffix):
            return suffix
    return None


def strip_fastq_suffix(name: str) -> str:
    lower = name.lower()
    for suffix in FASTQ_SUFFIXES:
        if lower.endswith(suffix):
            return name[:-len(suffix)]
    return name


def split_read_name(path: Path) -> tuple[str, str] | None:
    stem = strip_fastq_suffix(path.name)
    for suffix, read in (("_R1", "1"), ("_R2", "2")):
        if stem.casefold().endswith(suffix.casefold()):
            return stem[:-len(suffix)], read
    return None


def match_sample(label: str, records: dict[str, SubmissionRecord]) -> SubmissionRecord:
    matches = []
    for record in records.values():
        pattern = SAMPLE_BOUNDARY_RE.format(sample=re.escape(record.sample_id))
        if re.search(pattern, label, flags=re.IGNORECASE):
            matches.append(record)
    if len(matches) != 1:
        names = ", ".join(record.sample_id for record in matches)
        if not matches:
            raise ValueError(f"No submission Sample ID matches FASTQ label: {label}")
        raise ValueError(f"Multiple submission Sample IDs match FASTQ label {label}: {names}")
    return matches[0]


def discover_pairs(input_dir: Path, records: dict[str, SubmissionRecord]) -> tuple[list[FastqPair], list[PairResult]]:
    if not input_dir.is_dir():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")
    groups: dict[tuple[str, str, str], dict[str, object]] = {}
    mapping_errors: list[PairResult] = []
    for path in sorted(input_dir.rglob("*")):
        if not path.is_file() or fastq_suffix(path) is None:
            continue
        read_info = split_read_name(path)
        if read_info is None:
            continue
        stem, read = read_info
        try:
            record = match_sample(path.name, records)
        except ValueError as exc:
            mapping_errors.append(PairResult("", "", "", "", str(path), "", status="ERROR", error=str(exc)))
            continue
        key = (normalize_text(record.sample_id), str(path.parent), stem)
        group = groups.setdefault(key, {"record": record})
        if read in group:
            mapping_errors.append(PairResult(record.sample_id, record.barcode_candidate, record.barcode_name,
                                             record.barcode_sequence, str(path), "", status="ERROR",
                                             error=f"Duplicate R{read} file for pair stem {stem}"))
        else:
            group[read] = path

    pairs: list[FastqPair] = []
    for (_sample_key, _parent, stem), group in groups.items():
        record = group["record"]
        r1 = group.get("1")
        r2 = group.get("2")
        if not isinstance(record, SubmissionRecord):
            continue
        if not isinstance(r1, Path) or not isinstance(r2, Path):
            missing = "R1" if not isinstance(r1, Path) else "R2"
            mapping_errors.append(PairResult(record.sample_id, record.barcode_candidate, record.barcode_name,
                                             record.barcode_sequence, str(r1 or ""), str(r2 or ""), status="ERROR",
                                             error=f"Missing {missing} for pair stem {stem}"))
            continue
        pairs.append(FastqPair(record, stem, r1, r2))
    return pairs, mapping_errors


def discover_pairs_from_summary(summary_path: Path, input_dir: Path,
                                input_mode: str = "raw") -> tuple[list[FastqPair], list[PairResult]]:
    """Load match rows and resolve either fastp (raw) or supplied pre-split files."""
    if not summary_path.is_file():
        raise FileNotFoundError(f"Mapping summary not found: {summary_path}")
    errors: list[PairResult] = []
    pairs: list[FastqPair] = []
    seen: set[tuple[str, str, str]] = set()
    input_root = input_dir.resolve()
    with summary_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"pair_id", "sample_id", "barcode_candidate", "barcode_name",
                    "barcode_sequence", "status", "r1_path", "r2_path"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            # Transitional support for summaries written before the pair-level
            # contract.  New runs never enter this branch.
            return _discover_pairs_from_legacy_summary(summary_path, input_dir)
        for row in reader:
            status = display_text(row.get("status", "")).upper()
            pair_id = display_text(row.get("pair_id", "")).replace("\\", "/").strip("/")
            sample_id = display_text(row.get("sample_id", ""))
            candidate = display_text(row.get("barcode_candidate", ""))
            barcode_name = display_text(row.get("barcode_name", ""))
            sequence = display_text(row.get("barcode_sequence", "")).upper()
            raw_r1 = display_text(row.get("r1_path", ""))
            raw_r2 = display_text(row.get("r2_path", ""))
            if status != "OK":
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, raw_r1, raw_r2,
                                         status="ERROR", error=display_text(row.get("error", "mapping summary error"))))
                continue
            if not pair_id or any(part in {"", ".", ".."} for part in Path(pair_id).parts):
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, raw_r1, raw_r2,
                                         status="ERROR", error=f"Invalid pair_id in mapping summary: {pair_id!r}"))
                continue
            # A presplit FASTQ has already been demultiplexed, so barcode is
            # audit metadata only and may be absent from the match summary.
            # Raw input still requires the 8 bp primer barcode because it is
            # used to decide which reads are written to the sample output.
            barcode_required = input_mode != "presplit"
            if not sample_id or (barcode_required and not re.fullmatch(r"[ACGT]{8}", sequence)):
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, raw_r1, raw_r2,
                                         status="ERROR", error="Invalid sample/barcode fields in mapping summary"))
                continue
            relative_pair = Path(*pair_id.split("/"))
            # fastp publishes every pair under the canonical pair_id-derived
            # name, regardless of whether the source was raw or pre-split.
            # Prefer that path when the runner has just completed fastp.  A
            # direct standalone presplit invocation can still point at the
            # original tagged FASTQ, so fall back to the absolute paths from
            # the match summary when the canonical fastp pair is absent.
            canonical_r1 = input_dir / relative_pair.parent / f"{relative_pair.name}{CANONICAL_R1_SUFFIX}"
            canonical_r2 = input_dir / relative_pair.parent / f"{relative_pair.name}{CANONICAL_R2_SUFFIX}"
            if input_mode == "presplit" and canonical_r1.is_file() and canonical_r2.is_file():
                r1, r2 = canonical_r1, canonical_r2
            elif input_mode == "presplit":
                r1 = Path(raw_r1)
                r2 = Path(raw_r2)
                if not r1.is_absolute():
                    r1 = input_dir / r1
                if not r2.is_absolute():
                    r2 = input_dir / r2
            else:
                r1, r2 = canonical_r1, canonical_r2
            try:
                r1.resolve().relative_to(input_root)
                r2.resolve().relative_to(input_root)
            except ValueError:
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(r1), str(r2),
                                         status="ERROR", error="pair paths escape configured input directory"))
                continue
            if not r1.is_file() or not r2.is_file():
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(r1), str(r2),
                                         status="ERROR", error=("Pre-split R1/R2 file is missing" if input_mode == "presplit"
                                                                else "Canonical fastp R1/R2 output is missing")))
                continue
            key = (pair_id, normalize_text(sample_id), barcode_name)
            if key in seen:
                continue
            seen.add(key)
            pairs.append(FastqPair(SubmissionRecord(sample_id, candidate, barcode_name, sequence),
                                   relative_pair.name, r1, r2))

    physical_counts: dict[tuple[str, str], int] = {}
    sample_counts: dict[tuple[str, str, str], int] = {}
    for pair in pairs:
        physical = (str(pair.r1.resolve()), str(pair.r2.resolve()))
        physical_counts[physical] = physical_counts.get(physical, 0) + 1
        sample_key = physical + (normalize_text(pair.sample.sample_id),)
        sample_counts[sample_key] = sample_counts.get(sample_key, 0) + 1
    prepared: list[FastqPair] = []
    for pair in pairs:
        physical = (str(pair.r1.resolve()), str(pair.r2.resolve()))
        prefix = output_stem(pair.sample.sample_id)
        if sample_counts[physical + (normalize_text(pair.sample.sample_id),)] > 1:
            prefix = output_stem(f"{pair.sample.sample_id}__BC_{pair.sample.barcode_name}")
        prepared.append(FastqPair(pair.sample, pair.stem, pair.r1, pair.r2, prefix))
    return prepared, errors


def _discover_pairs_from_legacy_summary(summary_path: Path, input_dir: Path) -> tuple[list[FastqPair], list[PairResult]]:
    """Load the auditable file mapping produced by match_sample_barcode.py."""
    if not summary_path.is_file():
        raise FileNotFoundError(f"Mapping summary not found: {summary_path}")
    groups: dict[tuple[str, str, str], dict[str, object]] = {}
    errors: list[PairResult] = []

    # The summary records the raw-data path, while this branch now consumes
    # fastp output.  Resolve the same filename by matching the longest common
    # path suffix, because fastp preserves the raw relative directory tree.
    input_index: dict[str, list[Path]] = {}
    for candidate in input_dir.rglob("*"):
        if not candidate.is_file() or fastq_suffix(candidate) is None:
            continue
        input_index.setdefault(candidate.name.casefold(), []).append(candidate)
        if candidate.name.casefold().endswith(".gz"):
            input_index.setdefault(candidate.name[:-3].casefold(), []).append(candidate)
        else:
            input_index.setdefault((candidate.name + ".gz").casefold(), []).append(candidate)

    input_root = input_dir.resolve()

    def is_under_input(path: Path) -> bool:
        try:
            path.resolve().relative_to(input_root)
            return True
        except ValueError:
            return False

    def suffix_score(candidate: Path, source: Path) -> int:
        """Count matching path components from filename toward the parent.

        The mapping summary contains the raw absolute path, while fastp
        writes the same filename under the source-relative hierarchy.  A
        full suffix match (filename + parent + Lane/batch components) is much
        safer than matching only the basename when several batches reuse the
        same filename.
        """
        candidate_parts = [part.casefold() for part in candidate.parts]
        source_parts = [part.casefold() for part in source.parts]
        score = 0
        for left, right in zip(reversed(candidate_parts), reversed(source_parts)):
            if left != right:
                break
            score += 1
        return score

    def resolve_source(source: Path) -> Path:
        # Never reuse the original raw-data file when this stage is supposed
        # to consume fastp output.
        if source.is_file() and is_under_input(source):
            return source

        candidates = input_index.get(source.name.casefold(), [])
        if not candidates:
            return source
        if len(candidates) == 1:
            return candidates[0]

        scored = [(suffix_score(path, source), path) for path in candidates]
        best_score = max(score for score, _path in scored)
        best = [path for score, path in scored if score == best_score]
        # At least filename + one parent component must agree.  If a tie
        # remains, leave it unresolved so the row is reported as an error
        # instead of silently writing a flat/cross-batch output.
        if best_score >= 2 and len(best) == 1:
            return best[0]
        return source

    with summary_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"file_path", "read", "sample_id", "barcode_candidate", "barcode_name", "barcode_sequence", "status"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Mapping summary missing columns: {', '.join(sorted(missing))}")
        for row in reader:
            status = display_text(row.get("status", ""))
            file_value = display_text(row.get("file_path", ""))
            source = resolve_source(Path(file_value))
            if not source.is_absolute() and not source.exists():
                source = input_dir / source
            sample_id = display_text(row.get("sample_id", ""))
            candidate = display_text(row.get("barcode_candidate", ""))
            barcode_name = display_text(row.get("barcode_name", ""))
            sequence = display_text(row.get("barcode_sequence", "")).upper()
            if not is_under_input(source):
                errors.append(PairResult(
                    sample_id, candidate, barcode_name, sequence, str(source), "",
                    status="ERROR",
                    error="Cannot resolve mapping row to a file under fastp input directory",
                ))
                continue
            if status != "OK":
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(source), "",
                                         status="ERROR", error=display_text(row.get("error", "mapping summary error"))))
                continue
            if not sample_id or not re.fullmatch(r"[ACGT]{8}", sequence):
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(source), "",
                                         status="ERROR", error="Invalid sample/barcode fields in mapping summary"))
                continue
            read = display_text(row.get("read", "")).upper().lstrip("R")
            if read not in {"1", "2"}:
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(source), "",
                                         status="ERROR", error=f"Invalid read value in mapping summary: {read}"))
                continue
            read_info = split_read_name(source)
            if read_info is None:
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(source), "",
                                         status="ERROR", error=f"Cannot parse R1/R2 suffix from file path: {source.name}"))
                continue
            stem = read_info[0]
            key = (normalize_text(sample_id), str(source.parent), stem)
            record = SubmissionRecord(sample_id, candidate, barcode_name, sequence)
            group = groups.setdefault(key, {"record": record})
            previous = group.get("record")
            if previous != record:
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(source), "",
                                         status="ERROR", error=f"Conflicting mapping rows for pair {stem}"))
                continue
            if read in group:
                errors.append(PairResult(sample_id, candidate, barcode_name, sequence, str(source), "",
                                         status="ERROR", error=f"Duplicate R{read} row for pair {stem}"))
                continue
            group[read] = source

    pairs: list[FastqPair] = []
    for (_sample, _parent, stem), group in groups.items():
        record = group["record"]
        r1 = group.get("1")
        r2 = group.get("2")
        if not isinstance(record, SubmissionRecord):
            continue
        if not isinstance(r1, Path) or not isinstance(r2, Path):
            missing = "R1" if not isinstance(r1, Path) else "R2"
            errors.append(PairResult(record.sample_id, record.barcode_candidate, record.barcode_name,
                                     record.barcode_sequence, str(r1 or ""), str(r2 or ""), status="ERROR",
                                     error=f"Mapping summary has no {missing} for pair {stem}"))
            continue
        pairs.append(FastqPair(record, stem, r1, r2))
    physical_counts: dict[tuple[str, str], int] = {}
    physical_sample_counts: dict[tuple[tuple[str, str], str], int] = {}
    for pair in pairs:
        physical_key = (str(pair.r1.resolve()), str(pair.r2.resolve()))
        physical_counts[physical_key] = physical_counts.get(physical_key, 0) + 1
        sample_key = normalize_text(pair.sample.sample_id)
        count_key = (physical_key, sample_key)
        physical_sample_counts[count_key] = physical_sample_counts.get(count_key, 0) + 1
    prepared_pairs: list[FastqPair] = []
    for pair in pairs:
        physical_key = (str(pair.r1.resolve()), str(pair.r2.resolve()))
        output_prefix = ""
        if physical_counts[physical_key] > 1:
            # One physical pair matched multiple samples.  The prefix is used
            # as a sample subdirectory under <pair_stem>/, preventing outputs
            # from different samples/barcodes from being merged or overwritten.
            output_prefix = output_stem(pair.sample.sample_id)
            count_key = (physical_key, normalize_text(pair.sample.sample_id))
            if physical_sample_counts[count_key] > 1:
                output_prefix = output_stem(
                    f"{pair.sample.sample_id}__BC_{pair.sample.barcode_name}"
                )
        prepared_pairs.append(FastqPair(pair.sample, pair.stem, pair.r1, pair.r2, output_prefix))
    pairs = prepared_pairs
    return pairs, errors


def open_fastq(path: Path) -> TextIO:
    with path.open("rb") as probe:
        magic = probe.read(2)
    # Detect compression from the gzip magic, not merely the suffix.  This is
    # important for presplit inputs supplied as plain ``.fq`` files that are
    # temporarily exposed under the canonical ``.fq.gz`` output name.
    if magic == b"\x1f\x8b":
        return gzip.open(path, "rt", encoding="utf-8", errors="replace", newline="")
    return path.open("rt", encoding="utf-8", errors="replace", newline="")


def read_fastq_record(handle: TextIO) -> tuple[str, str, str, str] | None:
    header = handle.readline()
    if not header:
        return None
    seq = handle.readline()
    plus = handle.readline()
    qual = handle.readline()
    if not seq or not plus or not qual:
        raise ValueError("Truncated FASTQ record")
    header = header.rstrip("\r\n")
    seq = seq.rstrip("\r\n")
    plus = plus.rstrip("\r\n")
    qual = qual.rstrip("\r\n")
    if not header.startswith("@") or not plus.startswith("+"):
        raise ValueError(f"Invalid FASTQ record header/plus line: {header!r} / {plus!r}")
    if len(seq) != len(qual):
        raise ValueError(f"Sequence/quality length mismatch for {header}")
    return header, seq, plus, qual


UMI_HEADER_RE = re.compile(r"#(?:UMI:)?([ACGTN]+)$", flags=re.IGNORECASE)


def header_umi(header: str, umi_length: int) -> tuple[str, str]:
    """Return the canonical read ID and terminal UMI from a tagged FASTQ header.

    Both historical ``#UMI:ACGT...`` and the canonical ``#ACGT...`` forms are
    accepted so existing split output remains reusable.
    """
    token = header[1:].split(None, 1)[0]
    match = UMI_HEADER_RE.search(token)
    if not match:
        raise ValueError(f"Header has no terminal #UMI tag: {header}")
    umi = match.group(1).upper()
    if len(umi) != umi_length:
        raise ValueError(f"Header UMI length is {len(umi)}, expected {umi_length}: {header}")
    read_id = token[:match.start()]
    read_id = re.sub(r"/[12]$", "", read_id)
    if not read_id:
        raise ValueError(f"Header has an empty read ID: {header}")
    return read_id, umi


def write_umi_sidecar(fastq_path: Path, sidecar_path: Path, umi_length: int = UMI_LENGTH) -> None:
    """Persist read_id→UMI before clean_header removes the temporary tag."""
    temp_path = sidecar_path.with_name(f".{sidecar_path.name}.tmp")
    with open_fastq(fastq_path) as source, gzip.open(temp_path, "wt", encoding="utf-8", newline="") as target:
        target.write("read_id\tumi\n")
        while True:
            record = read_fastq_record(source)
            if record is None:
                break
            header = record[0]
            read_id, umi = header_umi(header, umi_length)
            target.write(f"{read_id}\t{umi}\n")
    os.replace(temp_path, sidecar_path)


def read_key(header: str) -> str:
    token = header[1:].split(None, 1)[0]
    return re.sub(r"/[12]$", "", token)


def add_umi(header: str, umi: str) -> str:
    body = header.rstrip("\r\n")
    parts = body.split(None, 1)
    first = f"{parts[0]}#{umi}"
    return first if len(parts) == 1 else f"{first} {parts[1]}"


def output_stem(stem: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "_", stem).strip(" .")
    return cleaned or "pair"


def _write_record(handle: TextIO, header: str, seq: str, plus: str, qual: str) -> None:
    handle.write(f"{header}\n{seq}\n{plus}\n{qual}\n")


def _relative_input_path(source: Path, input_dir: Path) -> Path:
    try:
        return source.resolve().relative_to(input_dir.resolve())
    except ValueError:
        return Path(source.name)


def _output_filename(source: Path) -> str:
    # Outputs are always gzip-compressed; make that explicit for plain inputs.
    return source.name if source.name.lower().endswith(".gz") else f"{source.name}.gz"


def _pair_key(pair: FastqPair) -> str:
    parent_digest = hashlib.sha1(str(pair.r1.resolve().parent).encode("utf-8")).hexdigest()[:8]
    return "|".join((pair.sample.sample_id, pair.sample.barcode_name, pair.stem, parent_digest))


def _input_fingerprint(pair: FastqPair, mode: str, umi_length: int) -> str:
    """Cheap, deterministic checkpoint identity for one physical pair.

    Size/mtime catches replaced upstream products without hashing terabytes of
    FASTQ on every resume. Barcode/UMI settings and the input mode are part of
    the key so a corrected mapping cannot reuse a stale partial output.
    """
    parts = [mode, str(umi_length), pair.sample.sample_id,
             pair.sample.barcode_name, pair.sample.barcode_sequence]
    for path in (pair.r1, pair.r2):
        try:
            stat = path.stat()
            parts.extend((str(path.resolve()), str(stat.st_size), str(stat.st_mtime_ns)))
        except OSError:
            parts.extend((str(path), "missing", "missing"))
    return hashlib.sha256("\0".join(parts).encode("utf-8")).hexdigest()


def _state_path(state_dir: Path, pair_key: str) -> Path:
    digest = hashlib.sha256(pair_key.encode("utf-8")).hexdigest()
    return state_dir / f"{digest}.json"


def _load_state(path: Path) -> dict[str, object]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            value = json.load(handle)
        return value if isinstance(value, dict) else {}
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {}


def _atomic_write_json(path: Path, value: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as handle:
            json.dump(value, handle, ensure_ascii=False, sort_keys=True)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass


def _progress_row(pair_key: str, result: PairResult, status: str | None = None) -> dict[str, str]:
    return {
        "pair_key": pair_key,
        "sample_id": result.sample_id,
        "r1": result.r1,
        "r2": result.r2,
        "output_r1": result.output_r1,
        "output_r2": result.output_r2,
        "processed_reads": str(result.processed_reads),
        "matched_reads": str(result.matched_reads),
        "mismatch_reads": str(result.mismatch_reads),
        "short_reads": str(result.short_reads),
        "status": status or result.status,
        "error": result.error,
        "updated_at": f"{time.time():.3f}",
    }


def _load_progress_summary(path: Path) -> None:
    global PROGRESS_ROWS
    PROGRESS_ROWS = {}
    if not path.is_file():
        return
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            for row in csv.DictReader(handle, delimiter="\t"):
                key = display_text(row.get("pair_key", ""))
                if key:
                    PROGRESS_ROWS[key] = {field: display_text(row.get(field, "")) for field in PROGRESS_FIELDS}
    except OSError:
        return


def _write_progress_summary(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(f".{path.name}.tmp")
    with temp.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=PROGRESS_FIELDS, delimiter="\t")
        writer.writeheader()
        for row in PROGRESS_ROWS.values():
            writer.writerow(row)
    os.replace(temp, path)


def _publish_progress(path: Path, row: dict[str, str], force: bool = False) -> None:
    global PROGRESS_UPDATES
    with PROGRESS_LOCK:
        PROGRESS_ROWS[row["pair_key"]] = row
        PROGRESS_UPDATES += 1
        if force or PROGRESS_UPDATES % max(1, PROGRESS_FLUSH_EVERY) == 0:
            _write_progress_summary(path)


def _display_progress(result: PairResult, pair_index: int = 0, pair_total: int = 0,
                      force: bool = False) -> None:
    interval = max(1, PROGRESS_DISPLAY_EVERY)
    if not force and result.processed_reads % interval:
        return
    match_pct = (result.matched_reads / result.processed_reads * 100) if result.processed_reads else 0.0
    pair_pct = (pair_index / pair_total * 100) if pair_total else 0.0
    pair_label = f"pair={pair_index}/{pair_total} ({pair_pct:.1f}%) " if pair_total else ""
    print(
        f"[split] {pair_label}{result.sample_id}/{result.barcode_name} "
        f"processed={result.processed_reads} matched={result.matched_reads} "
        f"match_rate={match_pct:.1f}% "
        f"status={result.status}",
        file=sys.stderr,
        flush=True,
    )


def _compress_part(part: Path, output: Path, compresslevel: int) -> None:
    temp = output.with_name(f".{output.name}.tmp")
    try:
        with part.open("rt", encoding="utf-8", newline="") as source, \
                gzip.open(temp, "wt", encoding="utf-8", newline="", compresslevel=compresslevel) as target:
            while True:
                chunk = source.read(1024 * 1024)
                if not chunk:
                    break
                target.write(chunk)
        os.replace(temp, output)
    finally:
        temp.unlink(missing_ok=True)


def _truncate_part_to_records(path: Path, records: int) -> bool:
    """Trim a resumed plain-text part to the last committed output record."""
    try:
        with path.open("rb") as handle:
            end = 0
            for _ in range(max(0, records) * 4):
                if not handle.readline():
                    return False
                end = handle.tell()
        with path.open("r+b") as handle:
            handle.truncate(end)
        return True
    except OSError:
        return False


def _write_pair(pair: FastqPair, output_dir: Path, input_dir: Path, umi_length: int,
                compresslevel: int, skip_existing: bool, progress_path: Path,
                state_dir: Path, pair_index: int = 0, pair_total: int = 0) -> PairResult:
    record = pair.sample
    relative_r1 = _relative_input_path(pair.r1, input_dir)
    relative_r2 = _relative_input_path(pair.r2, input_dir)
    base = output_stem(pair.stem)
    # Preserve the physical hierarchy for every pair:
    #   <output>/<Lane>/<original_pair_stem>/<sample_id>/<R1|R2 file>.gz
    # The sample leaf is required even when a FASTQ pair maps to only one
    # sample; otherwise all single-sample pairs in a Lane are collapsed into
    # one directory by clean/PANDAseq.  If an input already has the pair
    # directory (for example after a previous partial run), avoid adding the
    # same stem twice.
    pair_dir = output_dir / relative_r1.parent
    if pair_dir.name == base:
        pass
    elif pair_dir.parent.name == base:
        # Input already has <pair>/<sample>/<FASTQ>.
        pair_dir = pair_dir.parent
    else:
        pair_dir = pair_dir / base
    sample_dir = pair.output_prefix or output_stem(record.sample_id)
    out_dir = pair_dir / sample_dir
    output_name_r1 = _output_filename(relative_r1)
    output_name_r2 = _output_filename(relative_r2)
    output_r1 = out_dir / output_name_r1
    output_r2 = out_dir / output_name_r2
    umi_sidecar = out_dir / f"{output_r1.name}.umi.tsv.gz"
    result = PairResult(record.sample_id, record.barcode_candidate, record.barcode_name,
                        record.barcode_sequence, str(pair.r1), str(pair.r2), str(output_r1), str(output_r2))
    result.umi_sidecar = str(umi_sidecar)
    pair_key = _pair_key(pair)
    state_file = _state_path(state_dir, pair_key)
    input_fp = _input_fingerprint(pair, "raw", umi_length)
    part_r1 = output_r1.with_name(output_r1.name + ".part")
    part_r2 = output_r2.with_name(output_r2.name + ".part")
    state = _load_state(state_file) if skip_existing else {}
    if state and state.get("input_fingerprint") != input_fp:
        # Upstream FASTQ or barcode settings changed; never append to the old
        # part files because that would duplicate or mix records.
        state = {}
    # DONE is durable even when the runner has removed sequence payloads to
    # save disk.  This is what makes a later rerun process only new/fixed
    # mappings; incomplete pairs remain RUNNING/ERROR and are retried.
    # A DONE checkpoint is reusable only when every published payload still
    # exists.  The runner may remove sequence payloads to save disk, while
    # retaining state/sidecar metadata; do not report SKIPPED in that case or
    # a standalone rerun would silently leave the downstream FASTQ missing.
    if (state.get("status") == "DONE"
            and output_r1.is_file()
            and output_r2.is_file()
            and umi_sidecar.is_file()):
        for field in ("processed_reads", "total_reads", "matched_reads", "mismatch_reads", "short_reads"):
            try:
                setattr(result, field, int(state.get(field, 0)))
            except (TypeError, ValueError):
                pass
        result.status = "SKIPPED"
        _display_progress(result, pair_index, pair_total, force=True)
        _publish_progress(progress_path, _progress_row(pair_key, result, "SKIPPED"), force=True)
        return result

    try:
        resume_from = int(state.get("processed_reads", 0)) if state else 0
    except (TypeError, ValueError):
        resume_from = 0
    if resume_from > 0 and part_r1.exists() and part_r2.exists():
        try:
            with part_r1.open("rb") as probe:
                old_format = probe.read(2) == b"\x1f\x8b"
        except OSError:
            old_format = True
        if old_format:
            resume_from = 0
            part_r1.unlink(missing_ok=True)
            part_r2.unlink(missing_ok=True)
        else:
            try:
                expected_written = int(state.get("matched_reads", 0))
            except (TypeError, ValueError):
                expected_written = 0
            if not (_truncate_part_to_records(part_r1, expected_written)
                    and _truncate_part_to_records(part_r2, expected_written)):
                resume_from = 0
                part_r1.unlink(missing_ok=True)
                part_r2.unlink(missing_ok=True)
    if resume_from > 0 and part_r1.exists() and part_r2.exists():
        result.resumed_from = resume_from
        for field in ("total_reads", "matched_reads", "mismatch_reads", "short_reads"):
            try:
                setattr(result, field, int(state.get(field, 0)))
            except (TypeError, ValueError):
                pass
        result.processed_reads = resume_from
        _display_progress(result, pair_index, pair_total, force=True)
    else:
        resume_from = 0
        for part in (part_r1, part_r2):
            part.unlink(missing_ok=True)

    out_dir.mkdir(parents=True, exist_ok=True)
    trim_length = umi_length + len(record.barcode_sequence)
    try:
        with open_fastq(pair.r1) as r1_in, open_fastq(pair.r2) as r2_in:
            for _ in range(resume_from):
                previous_r1 = read_fastq_record(r1_in)
                previous_r2 = read_fastq_record(r2_in)
                if previous_r1 is None or previous_r2 is None:
                    raise ValueError("Saved checkpoint exceeds current FASTQ length")
                if read_key(previous_r1[0]) != read_key(previous_r2[0]):
                    raise ValueError("R1/R2 headers do not match before saved checkpoint")

            mode = "at" if resume_from else "wt"
            with part_r1.open(mode, encoding="utf-8", newline="") as r1_out, \
                    part_r2.open(mode, encoding="utf-8", newline="") as r2_out:
                while True:
                    r1 = read_fastq_record(r1_in)
                    r2 = read_fastq_record(r2_in)
                    if r1 is None and r2 is None:
                        break
                    if r1 is None or r2 is None:
                        raise ValueError("R1/R2 FASTQ record counts differ")
                    h1, s1, p1, q1 = r1
                    h2, s2, p2, q2 = r2
                    if read_key(h1) != read_key(h2):
                        raise ValueError(f"R1/R2 headers do not match: {h1} / {h2}")
                    result.total_reads += 1
                    result.processed_reads += 1
                    if len(s1) < trim_length:
                        result.short_reads += 1
                        result.mismatch_reads += 1
                    else:
                        umi = s1[:umi_length]
                        observed = s1[umi_length:trim_length].upper()
                        if observed == record.barcode_sequence:
                            result.matched_reads += 1
                            _write_record(r1_out, add_umi(h1, umi), s1[trim_length:], p1, q1[trim_length:])
                            _write_record(r2_out, add_umi(h2, umi), s2, p2, q2)
                        else:
                            result.mismatch_reads += 1
                    checkpoint_due = result.processed_reads % CHECKPOINT_EVERY == 0
                    if checkpoint_due:
                        # Commit output bytes before advancing the durable
                        # checkpoint.
                        r1_out.flush()
                        r2_out.flush()
                        state = {
                            "pair_key": pair_key,
                            "sample_id": result.sample_id,
                            "r1": result.r1,
                            "r2": result.r2,
                            "output_r1": result.output_r1,
                            "output_r2": result.output_r2,
                            "processed_reads": result.processed_reads,
                            "total_reads": result.total_reads,
                            "matched_reads": result.matched_reads,
                            "mismatch_reads": result.mismatch_reads,
                            "short_reads": result.short_reads,
                            "input_fingerprint": input_fp,
                            "status": "RUNNING",
                            "error": "",
                            "updated_at": time.time(),
                        }
                        _atomic_write_json(state_file, state)
                    _display_progress(result, pair_index, pair_total)
                    if checkpoint_due or result.processed_reads % PROGRESS_FLUSH_EVERY == 0:
                        _publish_progress(
                            progress_path,
                            _progress_row(pair_key, result, "RUNNING"),
                            force=checkpoint_due,
                        )
                # Flush data read after the last checkpoint before compression.
                r1_out.flush()
                r2_out.flush()
        _compress_part(part_r1, output_r1, compresslevel)
        _compress_part(part_r2, output_r2, compresslevel)
        part_r1.unlink(missing_ok=True)
        part_r2.unlink(missing_ok=True)
        write_umi_sidecar(output_r1, umi_sidecar)
        state.update({
            "pair_key": pair_key,
            "sample_id": result.sample_id,
            "r1": result.r1,
            "r2": result.r2,
            "output_r1": result.output_r1,
            "output_r2": result.output_r2,
            "umi_sidecar": str(umi_sidecar),
            "processed_reads": result.processed_reads,
            "total_reads": result.total_reads,
            "matched_reads": result.matched_reads,
            "mismatch_reads": result.mismatch_reads,
            "short_reads": result.short_reads,
            "input_fingerprint": input_fp,
        })
        state["status"] = "DONE"
        state["updated_at"] = time.time()
        _atomic_write_json(state_file, state)
        _display_progress(result, pair_index, pair_total, force=True)
        _publish_progress(progress_path, _progress_row(pair_key, result, "DONE"), force=True)
    except Exception as exc:
        result.status = "ERROR"
        result.error = str(exc)
        state = {
            "pair_key": pair_key,
            "sample_id": result.sample_id,
            "r1": result.r1,
            "r2": result.r2,
            "output_r1": result.output_r1,
            "output_r2": result.output_r2,
            "processed_reads": result.processed_reads,
            "total_reads": result.total_reads,
            "matched_reads": result.matched_reads,
            "mismatch_reads": result.mismatch_reads,
            "short_reads": result.short_reads,
            "input_fingerprint": input_fp,
            "status": "PARTIAL" if result.processed_reads else "ERROR",
            "error": result.error,
            "updated_at": time.time(),
        }
        _atomic_write_json(state_file, state)
        _display_progress(result, pair_index, pair_total, force=True)
        _publish_progress(progress_path, _progress_row(pair_key, result, state["status"]), force=True)
    return result


def _write_physical_group(group: list[FastqPair], output_dir: Path, input_dir: Path,
                          umi_length: int, compresslevel: int, skip_existing: bool,
                          progress_path: Path, state_dir: Path, group_index: int = 0,
                          group_total: int = 0) -> list[PairResult]:
    """Split one physical R1/R2 pair to all matched samples in one pass.

    A mixed raw pair can map to several barcode/sample rows.  The legacy
    worker model re-opened and decompressed that pair once per row.  This
    worker keeps one output stream per destination but reads the physical
    input exactly once, reducing I/O roughly in proportion to the number of
    mixed samples.  A partial mixed group is restarted atomically on the next
    run; independent groups retain the normal per-pair checkpoint behavior.
    """
    if not group:
        return []
    first = group[0]
    physical = (first.r1.resolve(), first.r2.resolve())
    if any((pair.r1.resolve(), pair.r2.resolve()) != physical for pair in group[1:]):
        raise ValueError("physical split group contains different FASTQ pairs")

    items: list[dict[str, object]] = []
    for pair in group:
        relative_r1 = _relative_input_path(pair.r1, input_dir)
        relative_r2 = _relative_input_path(pair.r2, input_dir)
        base = output_stem(pair.stem)
        pair_dir = output_dir / relative_r1.parent
        if pair_dir.name == base:
            pass
        elif pair_dir.parent.name == base:
            pair_dir = pair_dir.parent
        else:
            pair_dir = pair_dir / base
        out_dir = pair_dir / (pair.output_prefix or output_stem(pair.sample.sample_id))
        output_r1 = out_dir / _output_filename(relative_r1)
        output_r2 = out_dir / _output_filename(relative_r2)
        sidecar = out_dir / f"{output_r1.name}.umi.tsv.gz"
        result = PairResult(pair.sample.sample_id, pair.sample.barcode_candidate,
                            pair.sample.barcode_name, pair.sample.barcode_sequence,
                            str(pair.r1), str(pair.r2), str(output_r1), str(output_r2),
                            str(sidecar))
        pair_key = _pair_key(pair)
        state_file = _state_path(state_dir, pair_key)
        input_fp = _input_fingerprint(pair, "raw", umi_length)
        state = _load_state(state_file) if skip_existing else {}
        complete = (state.get("status") == "DONE"
                    and output_r1.is_file() and output_r2.is_file() and sidecar.is_file()
                    and state.get("input_fingerprint") == input_fp)
        items.append({"pair": pair, "result": result, "out_dir": out_dir,
                      "output_r1": output_r1, "output_r2": output_r2,
                      "sidecar": sidecar, "pair_key": pair_key,
                      "state_file": state_file, "input_fp": input_fp,
                      "complete": complete})

    if all(bool(item["complete"]) for item in items):
        results: list[PairResult] = []
        for item in items:
            result = item["result"]
            state = _load_state(item["state_file"])
            for field in ("processed_reads", "total_reads", "matched_reads", "mismatch_reads", "short_reads"):
                try:
                    setattr(result, field, int(state.get(field, 0)))
                except (TypeError, ValueError):
                    pass
            result.status = "SKIPPED"
            _display_progress(result, group_index, group_total, force=True)
            _publish_progress(progress_path, _progress_row(item["pair_key"], result, "SKIPPED"), force=True)
            results.append(result)
        return results

    handles: dict[tuple[int, str], TextIO] = {}
    try:
        for item_index, item in enumerate(items):
            out_dir = item["out_dir"]
            out_dir.mkdir(parents=True, exist_ok=True)
            for key, path in (("r1", item["output_r1"]), ("r2", item["output_r2"])):
                part = path.with_name(path.name + ".part")
                part.unlink(missing_ok=True)
                handles[(item_index, key)] = part.open("w", encoding="utf-8", newline="")

        with open_fastq(first.r1) as r1_in, open_fastq(first.r2) as r2_in:
            while True:
                r1 = read_fastq_record(r1_in)
                r2 = read_fastq_record(r2_in)
                if r1 is None and r2 is None:
                    break
                if r1 is None or r2 is None:
                    raise ValueError("R1/R2 FASTQ record counts differ")
                h1, s1, p1, q1 = r1
                h2, s2, p2, q2 = r2
                if read_key(h1) != read_key(h2):
                    raise ValueError(f"R1/R2 headers do not match: {h1} / {h2}")
                for item_index, item in enumerate(items):
                    result = item["result"]
                    result.total_reads += 1
                    result.processed_reads += 1
                    barcode = item["pair"].sample.barcode_sequence
                    trim_length = umi_length + len(barcode)
                    if len(s1) < trim_length:
                        result.short_reads += 1
                        result.mismatch_reads += 1
                        continue
                    umi = s1[:umi_length]
                    observed = s1[umi_length:trim_length].upper()
                    if observed != barcode:
                        result.mismatch_reads += 1
                        continue
                    result.matched_reads += 1
                    _write_record(handles[(item_index, "r1")], add_umi(h1, umi),
                                  s1[trim_length:], p1, q1[trim_length:])
                    _write_record(handles[(item_index, "r2")], add_umi(h2, umi), s2, p2, q2)

                processed = first_result = items[0]["result"]
                if processed.processed_reads % CHECKPOINT_EVERY == 0:
                    for handle in handles.values():
                        handle.flush()
                    for item in items:
                        result = item["result"]
                        _atomic_write_json(item["state_file"], {
                            "pair_key": item["pair_key"], "sample_id": result.sample_id,
                            "r1": result.r1, "r2": result.r2,
                            "output_r1": result.output_r1, "output_r2": result.output_r2,
                            "processed_reads": result.processed_reads,
                            "total_reads": result.total_reads,
                            "matched_reads": result.matched_reads,
                            "mismatch_reads": result.mismatch_reads,
                            "short_reads": result.short_reads,
                            "input_fingerprint": item["input_fp"],
                            "status": "RUNNING", "error": "", "updated_at": time.time(),
                        })
                        _publish_progress(progress_path,
                                          _progress_row(item["pair_key"], result, "RUNNING"))
        results = []
        for item in items:
            result = item["result"]
            for handle_key, handle in handles.items():
                if handle_key[0] == items.index(item):
                    handle.close()
            _compress_part(item["output_r1"].with_name(item["output_r1"].name + ".part"), item["output_r1"], compresslevel)
            _compress_part(item["output_r2"].with_name(item["output_r2"].name + ".part"), item["output_r2"], compresslevel)
            write_umi_sidecar(item["output_r1"], item["sidecar"], umi_length)
            item["output_r1"].with_name(item["output_r1"].name + ".part").unlink(missing_ok=True)
            item["output_r2"].with_name(item["output_r2"].name + ".part").unlink(missing_ok=True)
            _atomic_write_json(item["state_file"], {
                "pair_key": item["pair_key"], "sample_id": result.sample_id,
                "r1": result.r1, "r2": result.r2,
                "output_r1": result.output_r1, "output_r2": result.output_r2,
                "umi_sidecar": result.umi_sidecar,
                "processed_reads": result.processed_reads, "total_reads": result.total_reads,
                "matched_reads": result.matched_reads, "mismatch_reads": result.mismatch_reads,
                "short_reads": result.short_reads, "input_fingerprint": item["input_fp"],
                "status": "DONE", "error": "", "updated_at": time.time(),
            })
            result.status = "OK"
            _display_progress(result, group_index, group_total, force=True)
            _publish_progress(progress_path, _progress_row(item["pair_key"], result, "DONE"), force=True)
            results.append(result)
        return results
    except Exception as exc:
        for handle in handles.values():
            try:
                handle.close()
            except OSError:
                pass
        results = []
        for item in items:
            result = item["result"]
            result.status = "ERROR"
            result.error = str(exc)
            _atomic_write_json(item["state_file"], {
                "pair_key": item["pair_key"], "sample_id": result.sample_id,
                "r1": result.r1, "r2": result.r2,
                "output_r1": result.output_r1, "output_r2": result.output_r2,
                "processed_reads": result.processed_reads,
                "total_reads": result.total_reads, "matched_reads": result.matched_reads,
                "mismatch_reads": result.mismatch_reads, "short_reads": result.short_reads,
                "input_fingerprint": item["input_fp"], "status": "ERROR",
                "error": result.error, "updated_at": time.time(),
            })
            _publish_progress(progress_path, _progress_row(item["pair_key"], result, "ERROR"), force=True)
            results.append(result)
        return results


def _presplit_paths(pair: FastqPair, output_dir: Path, input_dir: Path) -> tuple[Path, Path, Path]:
    """Return the canonical stage-03 location for an externally split pair."""
    relative_r1 = _relative_input_path(pair.r1, input_dir)
    base = output_stem(pair.stem)
    pair_dir = output_dir / relative_r1.parent
    if pair_dir.name != base and pair_dir.parent.name != base:
        pair_dir = pair_dir / base
    elif pair_dir.parent.name == base:
        pair_dir = pair_dir.parent
    out_dir = pair_dir / (pair.output_prefix or output_stem(pair.sample.sample_id))
    return out_dir, out_dir / f"{base}{CANONICAL_R1_SUFFIX}", out_dir / f"{base}{CANONICAL_R2_SUFFIX}"


def _adopt_presplit_source(source: Path, destination: Path) -> None:
    """Expose an external pre-split FASTQ without mutating the source file."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() or destination.is_symlink():
        try:
            if destination.samefile(source):
                return
        except OSError:
            pass
        raise ValueError(f"Existing pre-split output has a different source: {destination}")
    with source.open("rb") as probe:
        is_gzip = probe.read(2) == b"\x1f\x8b"
    try:
        if not is_gzip:
            # The downstream contract uses canonical .fq.gz names.  A plain
            # external FASTQ therefore has to be compressed once; this is a
            # normalized stage-03 artifact and does not modify the source.
            fd, temp_name = tempfile.mkstemp(
                prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
            )
            os.close(fd)
            temp = Path(temp_name)
            try:
                with source.open("rb") as src, gzip.open(temp, "wb", compresslevel=1) as dst:
                    shutil.copyfileobj(src, dst, length=1024 * 1024)
                os.replace(temp, destination)
            finally:
                temp.unlink(missing_ok=True)
            return
        # ``find -type f`` is used by the downstream shell stages, so a
        # symlink would be invisible there.  A hard link is equally
        # non-destructive and remains a regular file; cross-filesystem inputs
        # fall back to a normal copy.
        os.link(source, destination)
    except OSError:
        # A copy is safe, though it costs disk; it is never modified or
        # deleted as part of source cleanup.
        shutil.copy2(source, destination)


def _prepare_presplit_pair(pair: FastqPair, output_dir: Path, input_dir: Path,
                           umi_length: int, skip_existing: bool, progress_path: Path,
                           state_dir: Path, pair_index: int = 0,
                           pair_total: int = 0) -> PairResult:
    """Validate tagged paired FASTQ and create the standard IR sidecar/input view."""
    out_dir, output_r1, output_r2 = _presplit_paths(pair, output_dir, input_dir)
    umi_sidecar = out_dir / f"{output_r1.name}.umi.tsv.gz"
    result = PairResult(pair.sample.sample_id, pair.sample.barcode_candidate,
                        pair.sample.barcode_name, pair.sample.barcode_sequence,
                        str(pair.r1), str(pair.r2), str(output_r1), str(output_r2),
                        str(umi_sidecar))
    pair_key = f"presplit|{_pair_key(pair)}"
    state_file = _state_path(state_dir, pair_key)
    input_fp = _input_fingerprint(pair, "presplit", umi_length)
    state = _load_state(state_file) if skip_existing else {}
    if state and state.get("input_fingerprint") != input_fp:
        state = {}
    if (state.get("status") == "DONE" and output_r1.is_file() and output_r2.is_file()
            and umi_sidecar.is_file()):
        for field in ("processed_reads", "total_reads", "matched_reads"):
            try:
                setattr(result, field, int(state.get(field, 0)))
            except (TypeError, ValueError):
                pass
        result.status = "SKIPPED"
        _display_progress(result, pair_index, pair_total, force=True)
        _publish_progress(progress_path, _progress_row(pair_key, result, "SKIPPED"), force=True)
        return result

    try:
        with open_fastq(pair.r1) as r1_in, open_fastq(pair.r2) as r2_in:
            while True:
                r1 = read_fastq_record(r1_in)
                r2 = read_fastq_record(r2_in)
                if r1 is None and r2 is None:
                    break
                if r1 is None or r2 is None:
                    raise ValueError("R1/R2 FASTQ record counts differ")
                read1, umi1 = header_umi(r1[0], umi_length)
                read2, umi2 = header_umi(r2[0], umi_length)
                if read1 != read2:
                    raise ValueError(f"R1/R2 read IDs do not match: {r1[0]} / {r2[0]}")
                if umi1 != umi2:
                    raise ValueError(f"R1/R2 UMI tags do not match for {read1}: {umi1}/{umi2}")
                result.total_reads += 1
                result.processed_reads += 1
                result.matched_reads += 1
                _display_progress(result, pair_index, pair_total)
        _adopt_presplit_source(pair.r1, output_r1)
        _adopt_presplit_source(pair.r2, output_r2)
        write_umi_sidecar(output_r1, umi_sidecar, umi_length)
        _atomic_write_json(state_file, {
            "pair_key": pair_key, "source_mode": "presplit", "sample_id": result.sample_id,
            "r1": result.r1, "r2": result.r2, "output_r1": result.output_r1,
            "output_r2": result.output_r2, "umi_sidecar": result.umi_sidecar,
            "processed_reads": result.processed_reads, "total_reads": result.total_reads,
            "matched_reads": result.matched_reads, "mismatch_reads": 0, "short_reads": 0,
            "input_fingerprint": input_fp,
            "status": "DONE", "error": "", "updated_at": time.time(),
        })
        _display_progress(result, pair_index, pair_total, force=True)
        _publish_progress(progress_path, _progress_row(pair_key, result, "DONE"), force=True)
    except Exception as exc:
        result.status = "ERROR"
        result.error = str(exc)
        _atomic_write_json(state_file, {
            "pair_key": pair_key, "source_mode": "presplit", "sample_id": result.sample_id,
            "r1": result.r1, "r2": result.r2, "output_r1": result.output_r1,
            "output_r2": result.output_r2, "processed_reads": result.processed_reads,
            "total_reads": result.total_reads, "matched_reads": result.matched_reads,
            "input_fingerprint": input_fp,
            "status": "ERROR", "error": result.error, "updated_at": time.time(),
        })
        _publish_progress(progress_path, _progress_row(pair_key, result, "ERROR"), force=True)
    return result


def _result_to_row(result: PairResult) -> dict[str, object]:
    denominator = result.total_reads or 0
    matched_pct = (result.matched_reads / denominator * 100) if denominator else 0.0
    mismatch_pct = (result.mismatch_reads / denominator * 100) if denominator else 0.0
    short_pct = (result.short_reads / denominator * 100) if denominator else 0.0
    processed_pct = (result.processed_reads / denominator * 100) if denominator else 0.0
    return {
        "sample_id": result.sample_id,
        "barcode_candidate": result.barcode_candidate,
        "barcode_name": result.barcode_name,
        "barcode_sequence": result.barcode_sequence,
        "r1": result.r1,
        "r2": result.r2,
        "output_r1": result.output_r1,
        "output_r2": result.output_r2,
        "umi_sidecar": result.umi_sidecar,
        "total_reads": result.total_reads,
        "matched_reads": result.matched_reads,
        "mismatch_reads": result.mismatch_reads,
        "short_reads": result.short_reads,
        "processed_reads": result.processed_reads,
        "resumed_from": result.resumed_from,
        "matched_pct": f"{matched_pct:.2f}",
        "mismatch_pct": f"{mismatch_pct:.2f}",
        "discarded_pct": f"{mismatch_pct:.2f}",
        "short_pct": f"{short_pct:.2f}",
        "processed_pct": f"{processed_pct:.2f}",
        "status": result.status,
        "error": result.error,
    }


def write_summary(path: Path, results: Iterable[PairResult]) -> None:
    fields = ["sample_id", "barcode_candidate", "barcode_name", "barcode_sequence", "r1", "r2",
              "output_r1", "output_r2", "umi_sidecar", "total_reads", "matched_reads", "mismatch_reads",
              "short_reads", "processed_reads", "resumed_from",
              "matched_pct", "mismatch_pct", "discarded_pct", "short_pct", "processed_pct",
              "status", "error"]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for result in results:
            writer.writerow(_result_to_row(result))


def main() -> int:
    if INPUT_MODE not in {"raw", "presplit"}:
        raise SystemExit("SCIGBLAST_IR_INPUT_MODE must be raw or presplit")
    if UMI_LENGTH < 0:
        raise SystemExit("UMI_LENGTH must be >= 0")
    if WORKERS < 1:
        raise SystemExit("WORKERS must be >= 1")
    if not 1 <= COMPRESSLEVEL <= 9:
        raise SystemExit("COMPRESSLEVEL must be between 1 and 9")
    if MAPPING_SUMMARY is None:
        raise SystemExit("MAPPING_SUMMARY must point to match_sample_barcode.py output")
    progress_path = PROGRESS_SUMMARY_PATH or OUTPUT_DIR / "ir_split_progress.tsv"
    state_dir = progress_path.parent / f".{progress_path.stem}_state"
    _load_progress_summary(progress_path)
    register_process()
    pairs, mapping_errors = discover_pairs_from_summary(MAPPING_SUMMARY, INPUT_DIR, INPUT_MODE)
    results: list[PairResult] = list(mapping_errors)
    print(f"Input mode={INPUT_MODE}; mapped {len(pairs)} FASTQ pair(s); mapping errors={len(mapping_errors)}", file=sys.stderr)
    if not pairs and not mapping_errors:
        raise SystemExit(f"No paired FASTQ files found under {INPUT_DIR}")
    if not DRY_RUN:
        if INPUT_MODE == "presplit":
            tasks: list[object] = list(pairs)

            def worker(item: object, index: int) -> object:
                pair = item
                if not isinstance(pair, FastqPair):
                    raise TypeError("invalid presplit task")
                return _prepare_presplit_pair(pair, OUTPUT_DIR, INPUT_DIR, UMI_LENGTH,
                                              SKIP_EXISTING, progress_path, state_dir,
                                              index, len(tasks))
        else:
            grouped: dict[tuple[str, str], list[FastqPair]] = {}
            for pair in pairs:
                key = (str(pair.r1.resolve()), str(pair.r2.resolve()))
                grouped.setdefault(key, []).append(pair)
            # One task per physical pair; a mixed pair can fan out to several
            # sample/barcode destinations without repeated decompression.
            tasks = [grouped[key] for key in grouped]

            def worker(item: object, index: int) -> object:
                if not isinstance(item, list) or not all(isinstance(x, FastqPair) for x in item):
                    raise TypeError("invalid raw split task")
                if len(item) > 1:
                    return _write_physical_group(item, OUTPUT_DIR, INPUT_DIR, UMI_LENGTH,
                                                 COMPRESSLEVEL, SKIP_EXISTING,
                                                 progress_path, state_dir, index, len(tasks))
                pair = item[0]
                return _write_pair(pair, OUTPUT_DIR, INPUT_DIR, UMI_LENGTH,
                                   COMPRESSLEVEL, SKIP_EXISTING, progress_path, state_dir,
                                   index, len(tasks))
        if WORKERS == 1 or len(tasks) < 2:
            for index, task in enumerate(tasks, 1):
                value = worker(task, index)
                results.extend(value if isinstance(value, list) else [value])
        else:
            with ThreadPoolExecutor(max_workers=min(WORKERS, len(tasks))) as executor:
                futures = [executor.submit(worker, task, index)
                           for index, task in enumerate(tasks, 1)]
                for future in as_completed(futures):
                    value = future.result()
                    results.extend(value if isinstance(value, list) else [value])
    else:
        results.extend(PairResult(pair.sample.sample_id, pair.sample.barcode_candidate, pair.sample.barcode_name,
                                  pair.sample.barcode_sequence, str(pair.r1), str(pair.r2), status="DRY_RUN")
                       for pair in pairs)

    summary_path = SUMMARY_PATH or OUTPUT_DIR / "ir_split_summary.csv"
    with PROGRESS_LOCK:
        _write_progress_summary(progress_path)
    results.sort(key=lambda result: (str(result.r1), str(result.sample_id), str(result.barcode_name)))
    write_summary(summary_path, results)
    error_count = sum(result.status == "ERROR" for result in results)
    ok_count = sum(result.status == "OK" for result in results)
    skipped_count = sum(result.status == "SKIPPED" for result in results)
    print(f"Done. OK={ok_count}, SKIPPED={skipped_count}, ERROR={error_count}, "
          f"summary={summary_path}, progress={progress_path}", file=sys.stderr)
    return 1 if error_count else 0


if __name__ == "__main__":
    raise SystemExit(main())
